
server:
  port: 8096

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
spring:
  data.mongodb:
    uri: mongodb://localhost:27017/moment
  autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
