server:
  port: 8092

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}   
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS

spring:
  data.mongodb:
    uri: mongodb://localhost:27017/cover
  datasource:
    url: jdbc:mysql://localhost/run?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: c7o2r1e4
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        
  
