server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
spring:
  datasource:
    url: jdbc:mysql://localhost/run
    username: root
    password: c7o2r1e4
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
